// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqkdsxxgjzicjrahpqan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa2RzeHhnanppY2pyYWhwcWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzIyNzQsImV4cCI6MjA2NDU0ODI3NH0._Oqkla9p5e0sZxR_9KUfMGUTV0UE1CShiJYItATZhDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);